---
all:
  hosts:
    awx-server:
      ansible_host: "{{ awx_host_ip }}"
      ansible_user: "{{ awx_ansible_user | default('ansible-svc') }}"
      ansible_become: true
      ansible_become_method: sudo
      ansible_ssh_private_key_file: "{{ awx_ssh_key_path | default('~/.ssh/id_ed25519') }}"
